set(CLX_OS_LAYER_DIR "${CMAKE_SOURCE_DIR}/src/conditionals/os/windows")
add_compile_definitions(OS_WINDOWS)

function(clx_os_check_core_headers)
    CHECK_INCLUDE_FILE("conio.h" CONIO_AVAILABLE)
    CHECK_INCLUDE_FILE("windows.h" WINDOWS_AVAILABLE)

    if(NOT CONIO_AVAILABLE)
        message(FATAL_ERROR "conio.h is required to build the compiler under windows")
    endif()
    if(NOT WINDOWS_AVAILABLE)
        message(FATAL_ERROR "windows.h is required to build the compiler under windows")
    endif()
endfunction()

function(clx_os_check_benchmark_headers)
    CHECK_INCLUDE_FILE("fileapi.h" FILEAPI_AVAILABLE)
    CHECK_INCLUDE_FILE("windows.h" WINDOWS_AVAILABLE)

    if(NOT FILEAPI_AVAILABLE)
        message(FATAL_ERROR "fileapi.h is required to build the benchmark runner under windows")
    endif()
    if(NOT WINDOWS_AVAILABLE)
        message(FATAL_ERROR "windows.h is required to build the benchmark runner under windows")
    endif()
endfunction()