:: Administrator permission is needed to install Cellox
@ECHO OFF
cd ..
ECHO Configuring CMake ...
cmake -B ./build -DCMAKE_BUILD_TYPE=Release
ECHO Building Interpreter ...
cmake --build ./build --config Release --target Cellox
ECHO Installing Interpreter ...
cmake --install ./build/src --config Release