@ECHO OFF
cd ..
ECHO Configuring CMake ...
cmake -B ./build -DCMAKE_BUILD_TYPE=Release
ECHO Building Interpreter ...
cmake --build ./build --config Release --target Cellox
cd .\build\src
ECHO Zipping cellox ...
cpack -G ZIP --config ../CPackConfig.cmake
:: Create an installer using NSIS (nullsoft scriptable install system) (https://sourceforge.net/projects/nsis/) for Windows
ECHO Creating installer using NSIS ...
cpack -G NSIS64 --config ../CPackConfig.cmake