@ECHO OFF
ECHO Configuring CMake for x64 ...
cmake -B ../build/gcc_x64 -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_C_COMPILER=C:/MinGW64/bin/gcc.exe
ECHO Building Interpreter for x64 ...
cmake --build ./build/gcc_x64 --config Release --target Cellox
ECHO Configuring CMake for x86 ...
cmake -B ../build/gcc_x86 -DCMAKE_BUILD_TYPE=Release -G Ninja -DCMAKE_C_COMPILER=C:/MinGW32/bin/gcc.exe
ECHO Building Interpreter for x86 ...
cmake --build ../build/gcc_x86 --config Release --target Cellox
cd ..\build\gcc_x64\src
ECHO Zipping cellox x64 ...
cpack -G ZIP --config ../CPackConfig.cmake
:: Create an installer using NSIS (nullsoft scriptable install system) (https://sourceforge.net/projects/nsis/) for Windows
ECHO Creating installer - x64 using NSIS ...
cpack -G NSIS64 --config ../CPackConfig.cmake
cd ..\..\gcc_x86\src
ECHO Zipping cellox x86 ...
cpack -G ZIP --config ../CPackConfig.cmake
:: Create an installer using NSIS (nullsoft scriptable install system) (https://sourceforge.net/projects/nsis/) for Windows
ECHO Creating installer - x86 using NSIS ...
cpack -G NSIS --config ../CPackConfig.cmake
cd ..\..\..\scripts