macro (cellox_add_os_compile_definitions)
    if(UNIX)
        add_compile_definitions(OS_UNIX_LIKE)    
    if(LINUX) 
        add_compile_definitions(OS_LINUX)
    elseif(APPLE) 
        add_compile_definitions(OS_MACOS)
    else()
        add_compile_definitions(OS_UNKNOWN_UNIX)
    endif()
    elseif(WIN32)
        add_compile_definitions(OS_WINDOWS)
    else()
        add_compile_definitions(OS_UNKNOWN)
    endif()
endmacro()

macro (cellox_add_compiler_compile_definitions)
    if(CMAKE_C_COMPILER_ID STREQUAL "GNU")
        add_compile_definitions(COMPILER_GCC)
    elseif(CMAKE_C_COMPILER_ID STREQUAL "Clang")
        add_compile_definitions(COMPILER_CLANG)
    elseif(CMAKE_C_COMPILER_ID STREQUAL "MSVC")
        add_compile_definitions(COMPILER_MSVC)
    elseif (CMAKE_C_COMPILER_ID STREQUAL "Intel")
        add_compile_definitions(COMPILER_INTEL)
    else()
        add_compile_definitions(COMPILER_UNKNOWN)
    endif()
endmacro()