name: Build Interpreter

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "dev" ]

env:
  BUILD_TYPE: ${{buildtype.types}}

jobs:
  build:
    runs-on: ${{ matrix.os }}

    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
            buildtype:
                types: [Debug, Release]    

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Interpreter
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target Cellox
      