name: Build Interpreter

on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{matrix.operatingsystems}}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}

    strategy:
      matrix:
        operatingsystems: [windows-latest, ubuntu-latest, macos-latest] 
        buildtypes: [Debug, Release] 

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Interpreter
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target Cellox
      