name: Build Tools
on:
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}    
    strategy:
            matrix:
                os: [ubuntu-latest, windows-latest, macos-latest]
                buildtypes: [Debug, Release]
    steps:
    - uses: actions/checkout@v3
    
    # Windoof setup
    - name: Setup Ninja under Windows
      if: runner.os == 'Windows'
      uses: ashutoshvarma/setup-ninja@master
      with:
        version: 1.10.2
    - name: Setup MSVC under Windows
      if: runner.os == 'Windows'
      uses: ilammy/msvc-dev-cmd@v1

    # Schlinux setup
    - name: Setup Ninja under Linux
      if: runner.os == 'Linux'
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          cmake \
          ninja-build \
          ${NULL+}

    # SchmockOS setup
    - name: Setup Ninja under MacOS
      if: runner.os == 'macOS'
      run: |
        brew install \
          ninja \
          ${NULL+}

    - name: Configure CMake
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -G Ninja -DCLX_BUILD_TOOLS=ON

    - name: Build compiler development tools
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target CelloxBenchmarks CelloxDisassembler
