name: Documentation

on:
  push:
    branches: [ master ]

jobs:
  build:
    name: Build and publish documentation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install Doxygen
      run:  sudo apt-get install doxygen
    - name: Generate documentation
      
      run: |
        cd src
        doxygen
    - name: Deploy to GitHub Pages
      uses: Cecilapp/GitHub-Pages-deploy@v3
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        email: ${{secrets.EMAIL}}
        build_dir: ./docs/html