name: Sanitizers
on:
  pull_request:
    branches: [ "master" ]

jobs:
  asan-ubsan:
    runs-on: ubuntu-latest
    env:
      BUILD_TYPE: Debug
    steps:
    - uses: actions/checkout@v3

    - name: Install toolchain
      run: |
        sudo apt-get update
        sudo apt-get -y install \
          clang \
          cmake \
          ninja-build \
          ${NULL+}

    - name: Configure CMake with sanitizers
      run: >
        cmake -B ${{github.workspace}}/build
        -G Ninja
        -DCLX_BUILD_TESTS=ON
        -DCLX_BUILD_TOOLS=OFF
        -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}
        -DCMAKE_C_COMPILER=clang
        -DCMAKE_CXX_COMPILER=clang++
        -DCMAKE_C_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer"
        -DCMAKE_CXX_FLAGS="-fsanitize=address,undefined -fno-omit-frame-pointer"

    - name: Build tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target CelloxUnitTests CelloxIntegrationTests CelloxE2ETests CelloxFuzzTests

    - name: Run tests under sanitizers
      working-directory: ${{github.workspace}}/build
      run: |
        ASAN_OPTIONS=detect_leaks=1:halt_on_error=1 \
        UBSAN_OPTIONS=print_stacktrace=1:halt_on_error=1 \
        ctest -C ${{env.BUILD_TYPE}} --output-on-failure
