name: Tests

on:
  pull_request:
    branches: [ "master" ]
  push:
    branches: [ "dev" ]  

strategy:  
  matrix:
    buildtypes: [Debug, Release]      

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_TYPE: ${{matrix.buildtypes}}

    steps:
    - uses: actions/checkout@v3

    - name: Configure CMake
        
      run: cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}

    - name: Build Tests
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}}

    - name: Test Interpreter
      working-directory: ${{github.workspace}}/build
      run: ctest -j 1 -C ${{env.BUILD_TYPE}}      
