name: googletest-project
on:
  push:
    paths-ignore:
    - 'resources/**'
    - 'README.md'

jobs:
  test-project:
    name: Test Project
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Test project with googletest.
      uses: arvsrao/googletest-action@master
